// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // TEMP_CUADREINVENTARIOS
    public class TempCuadreinventarioConfiguration : IEntityTypeConfiguration<TempCuadreinventario>
    {
        public void Configure(EntityTypeBuilder<TempCuadreinventario> builder)
        {
            builder.ToTable("TEMP_CUADREINVENTARIOS", "dbo");
            builder.HasKey(x => x.Iditemxcolor).HasName("RDB$PRIMARY12").IsClustered();

            builder.Property(x => x.Iditemxcolor).HasColumnName(@"IDITEMXCOLOR").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Pedidoinv).HasColumnName(@"PEDIDOINV").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Comprometido).HasColumnName(@"COMPROMETIDO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Cantproceso).HasColumnName(@"CANTPROCESO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Proceso).HasColumnName(@"PROCESO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Pedido).HasColumnName(@"PEDIDO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Entregado).HasColumnName(@"ENTREGADO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
