// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // TIPIDENTIFICA
    public class TipidentificaConfiguration : IEntityTypeConfiguration<Tipidentifica>
    {
        public void Configure(EntityTypeBuilder<Tipidentifica> builder)
        {
            builder.ToTable("TIPIDENTIFICA", "dbo");
            builder.HasKey(x => x.Idtipidentifica).HasName("PK_TIPIDENTIFICA").IsClustered();

            builder.Property(x => x.Idtipidentifica).HasColumnName(@"IDTIPIDENTIFICA").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Codtipidentifica).HasColumnName(@"CODTIPIDENTIFICA").HasColumnType("char(3)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(3);
            builder.Property(x => x.Nomtipidentifica).HasColumnName(@"NOMTIPIDENTIFICA").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);

            builder.HasIndex(x => x.Codtipidentifica).HasDatabaseName("UN_TIPIDENTIFICA_CODTIP").IsUnique();
            builder.HasIndex(x => x.Nomtipidentifica).HasDatabaseName("UN_TIPIDENTIFICA_NOMTIP").IsUnique();
        }
    }

}
// </auto-generated>
