// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // TIPOSACTXAREA
    public class TiposactxareaConfiguration : IEntityTypeConfiguration<Tiposactxarea>
    {
        public void Configure(EntityTypeBuilder<Tiposactxarea> builder)
        {
            builder.ToTable("TIPOSACTXAREA", "dbo");
            builder.HasKey(x => new { x.Idtipoactividad, x.Idarea }).HasName("PK_TIPOSACTXAREA").IsClustered();

            builder.Property(x => x.Idtipoactividad).HasColumnName(@"IDTIPOACTIVIDAD").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Idarea).HasColumnName(@"IDAREA").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);

            // Foreign keys
            builder.HasOne(a => a.Tiposactividad).WithMany(b => b.Tiposactxareas).HasForeignKey(c => c.Idtipoactividad).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_TIPOSACTXAREA_TIPOACT");
        }
    }

}
// </auto-generated>
