// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // TIPOSALARMAS
    public class TiposalarmaConfiguration : IEntityTypeConfiguration<Tiposalarma>
    {
        public void Configure(EntityTypeBuilder<Tiposalarma> builder)
        {
            builder.ToTable("TIPOSALARMAS", "dbo");
            builder.HasKey(x => x.Idtipo).HasName("PK_TIPOSALARMAS").IsClustered();

            builder.Property(x => x.Idtipo).HasColumnName(@"IDTIPO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Descripcion).HasColumnName(@"DESCRIPCION").HasColumnType("varchar(25)").IsRequired().IsUnicode(false).HasMaxLength(25);
            builder.Property(x => x.Alarmapordefecto).HasColumnName(@"ALARMAPORDEFECTO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Tabla).HasColumnName(@"TABLA").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Campo).HasColumnName(@"CAMPO").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
