// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // TIPOSACTIVIDAD
    public class TiposactividadConfiguration : IEntityTypeConfiguration<Tiposactividad>
    {
        public void Configure(EntityTypeBuilder<Tiposactividad> builder)
        {
            builder.ToTable("TIPOSACTIVIDAD", "dbo");
            builder.HasKey(x => x.Idtipoactividad).HasName("PK_TIPOSACTIVIDAD").IsClustered();

            builder.Property(x => x.Idtipoactividad).HasColumnName(@"IDTIPOACTIVIDAD").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Actividad).HasColumnName(@"ACTIVIDAD").HasColumnType("varchar(80)").IsRequired().IsUnicode(false).HasMaxLength(80);
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
