// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // TRASLADOS
    public class TrasladoConfiguration : IEntityTypeConfiguration<Traslado>
    {
        public void Configure(EntityTypeBuilder<Traslado> builder)
        {
            builder.ToTable("TRASLADOS", "dbo");
            builder.HasKey(x => x.Idtraslado).HasName("PK_TRASLADOS").IsClustered();

            builder.Property(x => x.Idtraslado).HasColumnName(@"IDTRASLADO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Fecha).HasColumnName(@"FECHA").HasColumnType("date").IsRequired();
            builder.Property(x => x.Idfuncionario).HasColumnName(@"IDFUNCIONARIO").HasColumnType("int").IsRequired();
            builder.Property(x => x.Idbodega).HasColumnName(@"IDBODEGA").HasColumnType("int").IsRequired();
            builder.Property(x => x.Observaciones).HasColumnName(@"OBSERVACIONES").HasColumnType("varchar(150)").IsRequired(false).IsUnicode(false).HasMaxLength(150);
            builder.Property(x => x.Idbodegadest).HasColumnName(@"IDBODEGADEST").HasColumnType("int").IsRequired();
            builder.Property(x => x.Fechacreacion).HasColumnName(@"FECHACREACION").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Nacionalizacion).HasColumnName(@"NACIONALIZACION").HasColumnType("varchar(30)").IsRequired(false).IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Trial928).HasColumnName(@"TRIAL928").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
