// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // UNIDADESMEDIDA
    public class UnidadesmedidaConfiguration : IEntityTypeConfiguration<Unidadesmedida>
    {
        public void Configure(EntityTypeBuilder<Unidadesmedida> builder)
        {
            builder.ToTable("UNIDADESMEDIDA", "dbo");
            builder.HasKey(x => x.Idunidad).HasName("PK_UNIDADESMEDIDA").IsClustered();

            builder.Property(x => x.Idunidad).HasColumnName(@"IDUNIDAD").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Nombre).HasColumnName(@"NOMBRE").HasColumnType("varchar(30)").IsRequired().IsUnicode(false).HasMaxLength(30);
            builder.Property(x => x.Trial931).HasColumnName(@"TRIAL931").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);

            builder.HasIndex(x => x.Nombre).HasDatabaseName("UN_UNIDADESMEDIDA_NOMBRE").IsUnique();
        }
    }

}
// </auto-generated>
