// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // USUARIOS
    public class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> builder)
        {
            builder.ToTable("USUARIOS", "dbo");
            builder.HasKey(x => x.Idusuario).HasName("PK_USUARIOS").IsClustered();

            builder.Property(x => x.Idusuario).HasColumnName(@"IDUSUARIO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Login).HasColumnName(@"LOGIN").HasColumnType("varchar(15)").IsRequired().IsUnicode(false).HasMaxLength(15);
            builder.Property(x => x.Usahorario).HasColumnName(@"USAHORARIO").HasColumnType("char(1)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.Aplicanfestivos).HasColumnName(@"APLICANFESTIVOS").HasColumnType("char(1)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.Activo).HasColumnName(@"ACTIVO").HasColumnType("char(1)").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            builder.Property(x => x.Idfuncionario).HasColumnName(@"IDFUNCIONARIO").HasColumnType("int").IsRequired();
            builder.Property(x => x.Clave1).HasColumnName(@"CLAVE1").HasColumnType("varchar(20)").IsRequired().IsUnicode(false).HasMaxLength(20);
            builder.Property(x => x.Trial931).HasColumnName(@"TRIAL931").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
