// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // USUARIOSCORREOSEGUIMIENTO
    public class UsuarioscorreoseguimientoConfiguration : IEntityTypeConfiguration<Usuarioscorreoseguimiento>
    {
        public void Configure(EntityTypeBuilder<Usuarioscorreoseguimiento> builder)
        {
            builder.ToTable("USUARIOSCORREOSEGUIMIENTO", "dbo");
            builder.HasKey(x => x.Idfuncionario).HasName("PK_USUARIOSCORREOSEGUIMIENTO").IsClustered();

            builder.Property(x => x.Idfuncionario).HasColumnName(@"IDFUNCIONARIO").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Correosalida).HasColumnName(@"CORREOSALIDA").HasColumnType("varchar(100)").IsRequired().IsUnicode(false).HasMaxLength(100);
            builder.Property(x => x.Trial931).HasColumnName(@"TRIAL931").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
