// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ModelGeneratorContext
{
    // VALIDACIONCOMPROMETIDOS
    public class ValidacioncomprometidoConfiguration : IEntityTypeConfiguration<Validacioncomprometido>
    {
        public void Configure(EntityTypeBuilder<Validacioncomprometido> builder)
        {
            builder.ToTable("VALIDACIONCOMPROMETIDOS", "dbo");
            builder.HasKey(x => x.Iditemxcolor).HasName("PK_VALIDACIONCOMPROMETIDOS").IsClustered();

            builder.Property(x => x.Iditemxcolor).HasColumnName(@"IDITEMXCOLOR").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Pedidoinv).HasColumnName(@"PEDIDOINV").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Comprometido).HasColumnName(@"COMPROMETIDO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Cantproceso).HasColumnName(@"CANTPROCESO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Proceso).HasColumnName(@"PROCESO").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Trial931).HasColumnName(@"TRIAL931").HasColumnType("char(1)").IsRequired(false).IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
