// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class AldebaranContext : DbContext, IAldebaranContext
    {
        public AldebaranContext()
        {
        }

        public AldebaranContext(DbContextOptions<AldebaranContext> options)
            : base(options)
        {
        }

        public DbSet<TempCuadreinventario> TempCuadreinventarios { get; set; } // TEMP_CUADREINVENTARIOS
        public DbSet<Tipidentifica> Tipidentificas { get; set; } // TIPIDENTIFICA
        public DbSet<Tiposactividad> Tiposactividads { get; set; } // TIPOSACTIVIDAD
        public DbSet<Tiposactxarea> Tiposactxareas { get; set; } // TIPOSACTXAREA
        public DbSet<Tiposalarma> Tiposalarmas { get; set; } // TIPOSALARMAS
        public DbSet<Traslado> Trasladoes { get; set; } // TRASLADOS
        public DbSet<Unidadesmedida> Unidadesmedidas { get; set; } // UNIDADESMEDIDA
        public DbSet<Usuario> Usuarios { get; set; } // USUARIOS
        public DbSet<Usuarioscorreoseguimiento> Usuarioscorreoseguimientoes { get; set; } // USUARIOSCORREOSEGUIMIENTO
        public DbSet<Validacioncomprometido> Validacioncomprometidoes { get; set; } // VALIDACIONCOMPROMETIDOS

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=DESKTOP-NRVP3JS;Initial Catalog=ALDEBARAN;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new TempCuadreinventarioConfiguration());
            modelBuilder.ApplyConfiguration(new TipidentificaConfiguration());
            modelBuilder.ApplyConfiguration(new TiposactividadConfiguration());
            modelBuilder.ApplyConfiguration(new TiposactxareaConfiguration());
            modelBuilder.ApplyConfiguration(new TiposalarmaConfiguration());
            modelBuilder.ApplyConfiguration(new TrasladoConfiguration());
            modelBuilder.ApplyConfiguration(new UnidadesmedidaConfiguration());
            modelBuilder.ApplyConfiguration(new UsuarioConfiguration());
            modelBuilder.ApplyConfiguration(new UsuarioscorreoseguimientoConfiguration());
            modelBuilder.ApplyConfiguration(new ValidacioncomprometidoConfiguration());
        }

    }
}
// </auto-generated>
