// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace ModelGeneratorContext
{
    public class AldebaranContextFactory : IDesignTimeDbContextFactory<AldebaranContext>
    {
        public AldebaranContext CreateDbContext(string[] args)
        {
            return new AldebaranContext();
        }
    }
}
// </auto-generated>
