CREATE TABLE ERPShippingProcessDetail
 (ID INT NOT NULL CONSTRAINT PK_ERPShippingProcessDetail PRIMARY KEY,
  IDERPSHIPPINGPROCESS INT NOT NULL CONSTRAINT FK_ERPShippingProcess REFERENCES ERPShippingProcess (ID),
  IDERPDOCUMENTTYPE INT NOT NULL CONSTRAINT FK_ERPDocumentType REFERENCES ERPDocumentType (ID),
  IDDOCUMENT INT NOT NULL, 
  FILENAME VARCHAR(30)); 
  