CREATE VIEW ERPItems
AS
SELECT ic.IDITEMXCOLOR, l.CODLINEA, l.NOMLINEA, i.REFINTERNA, i.NOMITEM, ic.REFITEMXCOLOR, ic.NOMCOLOR 
  FROM ITEMSXCOLOR ic
  JOIN ITEMS i ON i.IDITEM = ic.IDITEM
  JOIN LINEAS l ON l.IDLINEA = i.IDLINEA
 WHERE i.TIPOITEM = 'C'
 ORDER BY ic.IDITEMXCOLOR