CREATE TABLE ERPDocumentType
(ID INT NOT NULL CONSTRAINT PK_ERPDocumentType PRIMARY KEY,
 NAME VARCHAR(30) NOT NULL,
 CodeType Char(1) NOT NULL,
 LastExecutionDate TIMESTAMP NOT NULL,
 LastCleaningDate TIMESTAMP NOT NULL);