INSERT INTO ERPDocumentType
     VALUES (1,'ORDEN DE COMPRA','O', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ERPDocumentType
     VALUES (2,'PEDIDO','P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);