// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // TEMP_CUADREINVENTARIOS
    /// <summary>
    /// TRIAL
    /// </summary>
    public class TempCuadreinventario
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Iditemxcolor { get; set; } // IDITEMXCOLOR (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Pedidoinv { get; set; } // PEDIDOINV

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Comprometido { get; set; } // COMPROMETIDO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Cantproceso { get; set; } // CANTPROCESO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Proceso { get; set; } // PROCESO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Pedido { get; set; } // PEDIDO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Entregado { get; set; } // ENTREGADO

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)
    }

}
// </auto-generated>
