// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // TIPIDENTIFICA
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Tipidentifica
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idtipidentifica { get; set; } // IDTIPIDENTIFICA (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Codtipidentifica { get; set; } // CODTIPIDENTIFICA (length: 3)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Nomtipidentifica { get; set; } // NOMTIPIDENTIFICA (length: 30)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)
    }

}
// </auto-generated>
