// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // TIPOSACTIVIDAD
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Tiposactividad
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idtipoactividad { get; set; } // IDTIPOACTIVIDAD (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Actividad { get; set; } // ACTIVIDAD (length: 80)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)

        // Reverse navigation

        /// <summary>
        /// Child Tiposactxareas where [TIPOSACTXAREA].[IDTIPOACTIVIDAD] point to this entity (FK_TIPOSACTXAREA_TIPOACT)
        /// </summary>
        public ICollection<Tiposactxarea> Tiposactxareas { get; set; } // TIPOSACTXAREA.FK_TIPOSACTXAREA_TIPOACT

        public Tiposactividad()
        {
            Tiposactxareas = new List<Tiposactxarea>();
        }
    }

}
// </auto-generated>
