// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // TIPOSACTXAREA
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Tiposactxarea
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idtipoactividad { get; set; } // IDTIPOACTIVIDAD (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idarea { get; set; } // IDAREA (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)

        // Foreign keys

        /// <summary>
        /// Parent Tiposactividad pointed by [TIPOSACTXAREA].([Idtipoactividad]) (FK_TIPOSACTXAREA_TIPOACT)
        /// </summary>
        public Tiposactividad Tiposactividad { get; set; } // FK_TIPOSACTXAREA_TIPOACT
    }

}
// </auto-generated>
