// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // TIPOSALARMAS
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Tiposalarma
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idtipo { get; set; } // IDTIPO (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Descripcion { get; set; } // DESCRIPCION (length: 25)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Alarmapordefecto { get; set; } // ALARMAPORDEFECTO

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Tabla { get; set; } // TABLA (length: 30)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Campo { get; set; } // CAMPO (length: 30)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)

        public Tiposalarma()
        {
            Descripcion = "";
        }
    }

}
// </auto-generated>
