// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // TRASLADOS
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Traslado
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idtraslado { get; set; } // IDTRASLADO (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Fecha { get; set; } // FECHA

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idfuncionario { get; set; } // IDFUNCIONARIO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idbodega { get; set; } // IDBODEGA

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Observaciones { get; set; } // OBSERVACIONES (length: 150)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idbodegadest { get; set; } // IDBODEGADEST

        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Fechacreacion { get; set; } // FECHACREACION

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Nacionalizacion { get; set; } // NACIONALIZACION (length: 30)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial928 { get; set; } // TRIAL928 (length: 1)

        public Traslado()
        {
            Fechacreacion = DateTime.Now;
        }
    }

}
// </auto-generated>
