// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // UNIDADESMEDIDA
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Unidadesmedida
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idunidad { get; set; } // IDUNIDAD (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Nombre { get; set; } // NOMBRE (length: 30)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial931 { get; set; } // TRIAL931 (length: 1)
    }

}
// </auto-generated>
