// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // USUARIOS
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Usuario
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idusuario { get; set; } // IDUSUARIO (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Login { get; set; } // LOGIN (length: 15)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Usahorario { get; set; } // USAHORARIO (length: 1)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Aplicanfestivos { get; set; } // APLICANFESTIVOS (length: 1)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Activo { get; set; } // ACTIVO (length: 1)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idfuncionario { get; set; } // IDFUNCIONARIO

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Clave1 { get; set; } // CLAVE1 (length: 20)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial931 { get; set; } // TRIAL931 (length: 1)
    }

}
// </auto-generated>
