// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // USUARIOSCORREOSEGUIMIENTO
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Usuarioscorreoseguimiento
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Idfuncionario { get; set; } // IDFUNCIONARIO (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Correosalida { get; set; } // CORREOSALIDA (length: 100)

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial931 { get; set; } // TRIAL931 (length: 1)
    }

}
// </auto-generated>
