// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ModelGeneratorContext
{
    // VALIDACIONCOMPROMETIDOS
    /// <summary>
    /// TRIAL
    /// </summary>
    public class Validacioncomprometido
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Iditemxcolor { get; set; } // IDITEMXCOLOR (Primary key)

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Pedidoinv { get; set; } // PEDIDOINV

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Comprometido { get; set; } // COMPROMETIDO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Cantproceso { get; set; } // CANTPROCESO

        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Proceso { get; set; } // PROCESO

        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial931 { get; set; } // TRIAL931 (length: 1)
    }

}
// </auto-generated>
